build: add 10.13.4
owncloud-docker/appliance pull request #212
Opened 2023-12-13 21:23 UTC by jnweiger

2023-12-13 22:10 UTC, xoxys requested changes
New config option to suppress ioc not implemented.

2023-12-14 17:11 UTC, jnweiger commented
Implemented in https://github.com/owncloud-docker/base/pull/321

2023-12-15 10:35 UTC, phil-davis approved these changes
Looks OK

2023-12-15 10:53 UTC, xoxys approved these changes

2023-12-15 10:53 UTC, merged